### ISSUE TITLE
code to normalize numbers to german spoken words

### ISSUE THREAD

**Issue by AASHISHAG** [ynop/audiomate#122]
hi, thank you for this awesome repo. 

is there any module in audiomate that could be used normalise numbers to german spoken words?

**Comment by ynop** [comment]
No, but there is num2words which does exactly that. 
I used it here: https://github.com/ynop/spoteno/blob/master/spoteno/steps/numbers.py

**Comment by AASHISHAG** [comment]
thank you for the link. 

do you also have any recommendation for words2num ?

i tried this, but it doesn't seem to work.

https://pypi.org/project/words2num/

**Comment by ynop** [comment]
No, the other way around I also searched some time ago, but without any success.
