### ISSUE TITLE
Kaldi I/O type error

### ISSUE THREAD

**Issue by Tortoise17** [ynop/audiomate#127]
Dear friend. 

as I suppose, the audiomate is handling lot of formats very efficiently and perfectly. 

but, there is one format issue. Maybe you can understand. 
while data preparation, it throws error below

File "/home/user/anaconda3/envs/zml/lib/python3.6/site-packages/audiomate/corpus/corpus.py", line 123, in load
    return reader.load(path)
  File "/home/user/anaconda3/envs/zml/lib/python3.6/site-packages/audiomate/corpus/io/base.py", line 95, in load
    self.type(), ' '.join(missing_files), path))

OSError: Invalid data set of type kaldi: files wav.scp text not found at data/swc

The data in each folder is consisting files below.  
aligned.swc
audio.ogg
audiometa.txt
info.json
wiki.html
wiki.html
wiki.xml

Do I need to run any script first to convert these formats? or ?any of the library is ignored by me to install. 
Can you comment? why is it so? or any script to resolve and make like to be useable for audiomate.

**Comment by ynop** [comment]
This seems to be the SWC dataset?

You need to use the swc reader:
```reader='swc'```

**Comment by Tortoise17** [comment]
This is a great help. I would like to ask only one more question. with SWC data, deepspeech is throwing error for character limitations for long length words. Do you have any idea how to manage it?
