### ISSUE TITLE
Updating license

### ISSUE THREAD

**Issue by DanBmh** [ynop/audiomate#130]
I'd like to add some new datasets and improved features (see https://github.com/ynop/audiomate/pull/129), but I'd also like to update the licence for this (MIT->LGPL).

I'm developing all of this in my free time and want to make sure that everyone who uses and extends it also contributes back again, that it becomes an exchange of work and time.
I also had some bad experiences with a partly open source and partly proprietary project where I put a lot of time into and which I can't use any more because the community support was stopped and development is now continued proprietary. That's why I generally prefer (weak) copyleft licenses. (Not that I believe this will happen here.)

Using LGPL shouldn't affect any users, so from my point of view it has no negative consequences except the effort of the changing process, but ensures the exchange of work.

**Comment by aahlenst** [comment]
Anything more restrictive than the Apache Software License (which the LGPL is) has been a problem in the past when it comes to collaboration with US universities. This is something I want to avoid. Lack of funding or collaboration barriers are the biggest threat to the continued development of this project, so your proposal might have the opposite effect.

Even with the LGPL, there's no guarantee that development continues in the open. We used JPedal (a Java library) in the past that was licensed under the LGPL. The source code was removed and development happens behind a curtain.

Regardless of my concerns and that I do not think that the proposal has the desired impact, there are two bars to clear:

* Significant support by contributors and users for this change
* @ynop's and my work is owned by our university. They have to agree. If not, 90% or so of the code need to be replaced.

**Comment by DanBmh** [comment]
For the first point I did check the number of contributors (with lines of code) with the snippet I found [here](https://www.programming-books.io/essential/git/lines-of-code-per-developer-9a4852d672d0442dbff5aba48c9c6b5a)

This gives me:
```
  44131 buec
   1192 Andreas Ahlenstorf
   1084 Daniel
     55 Chetan Kini
     42 Matthias
     23 Armin
      6 Fabian-Robert Stöter
      4 Vojtěch Drábek
      3 Todd
      2 DanBmh
```
Unlike the github insights this also counts contributions without a valid email (like mine^^).
