### ISSUE TITLE
Add MUSDB18 corpus

### ISSUE THREAD

**Issue by JoshuaStorm** [ynop/audiomate#63]
See:
https://sigsep.github.io/datasets/musdb.html

Seems like a very valuable dataset that is worth adding if someone has the time!

**Comment by ynop** [comment]
Thanks for the hint!

It is already on the list of datasets (#44). Currently I am busy with other stuff. But if you want to give it a try, see https://audiomate.readthedocs.io/en/latest/documentation/new_dataset_format.html. Any contributions are welcomed.

**Comment by JoshuaStorm** [comment]
Ah, my bad! Looking a little into it, it might be difficult since they have to vet individuals requesting the data set

**Comment by faroit** [comment]
Great Project!

Concerning musdb, we now have a 30s and a 7s preview version of the dataset under creative commons (currently only as WAV files https://zenodo.org/record/1256003 at https://zenodo.org/record/1256064). As soon as I have uploaded the compressed dataset I can make a PR.
