### ISSUE TITLE
Feeding notebook example broken

### ISSUE THREAD

**Issue by Abhipray** [ynop/audiomate#81]
It appears that the feeding notebook example is broken for generating the targets container.  The issue is that if a Label has its `end` variable set to `inf`, `units.seconds_to_sample()` encounters an overflow. 

My fix for the issue was to set the end field in each label to the be the end of the utterance in my Corpus reader.

**Comment by ynop** [comment]
Thanks for the info.

Fixed it in be27b0de7191d4cf05a89cb92eee07e152ce2a0b and d7fd49c3dfed50f7109f359bda6d13ed32452e6a.

Now it makes the correct check, if the label end is defined as the end of the utterance.
