### ISSUE TITLE
Check existence of folder in CorpusReader

### ISSUE THREAD

**Issue by ynop** [ynop/audiomate#89]
For some readers there is no error when the path to load doesn't even exist.
So one could assume the loading was successful.
Add a check in the base-class to check if the path exists.

**Comment by cdkini** [comment]
@ynop can I tackle this issue? I'd imagine the approach is quite similar to my prior PR with CorpusDownloader.

**Comment by ynop** [comment]
Sure. Yes, it should be similar. I would say just throw an IOError, if the path doesn't exist at all.
