### ISSUE TITLE
Generate subset with utterences <x seconds?

### ISSUE THREAD

**Issue by olafthiele** [ynop/audiomate#95]
Is there currently a way to create a subset that takes only utterances up to a certain length? 

Great project, thanks

**Comment by ynop** [comment]
No, there is not.

But it is easy to do that:

```python
from audiomate.corpus import subset

ids = set()
for utt in corpus.utterances.values():
    if utt.duration < threshold:
        ids.add(utt.idx)

filter = subset.MatchingUtteranceIdxFilter(utterance_idxs=ids)
your_subset = subset.Subview(corpus, filter_criteria=[filter])
```
Haven't tested it, but something like that should work.

If you'd like to add the functionality feel free to open a pull request.
I guess it would fit into audiomate/corpus/subset/selection.py as a new method.

**Comment by olafthiele** [comment]
Thanks, will try that quick and dirty this week and take the time to write a nice version next week with pull request.
